### ISSUE TITLE
Tables are broken

### ISSUE THREAD

**Issue by NamanShergill** [daohoangson/flutter_widget_from_html#1066]
## Steps to Reproduce
The tables in the repo https://github.com/firebase/flutterfire readme can be used to debug.

<details>
  <summary>HTML</summary>

```html
      <p align="center">
  <a href="https://firebase.google.com/docs/flutter" rel="nofollow">
    <img width="250px" src=".github/images/flutterfire_300x.png" alt="Flutter + Firebase logo" style="max-width: 100%;"><br>
  </a>
  </p><h1 align="center">FlutterFire</h1>
<p></p>
<p align="center">
  <a href="https://twitter.com/flutterfiredev" rel="nofollow">
    <img src="https://camo.githubusercontent.com/24d746561fe2a272aa9321201132dfecddb381d6f1eb2b33a9fa0057be6b7a13/68747470733a2f2f696d672e736869656c64732e696f2f747769747465722f666f6c6c6f772f666c7574746572666972656465762e7376673f636f6c6f72413d31646131663226636f6c6f72423d266c6162656c3d466f6c6c6f772532306f6e25323054776974746572267374796c653d666c61742d737175617265" alt="Follow on Twitter" data-canonical-src="https://img.shields.io/twitter/follow/flutterfiredev.svg?colorA=1da1f2&amp;colorB=&amp;label=Follow%20on%20Twitter&amp;style=flat-square" style="max-width: 100%;">
  </a>
  <a href="https://github.com/invertase/melos">
    <img src="https://camo.githubusercontent.com/8c37b07a43ee68d919c890bdc57f0c6a0cc670c923be6655ad9c4b437248d015/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f6d61696e7461696e6564253230776974682d6d656c6f732d6637303066662e7376673f7374796c653d666c61742d737175617265" alt="Maintained with Melos" data-canonical-src="https://img.shields.io/badge/maintained%20with-melos-f700ff.svg?style=flat-square" style="max-width: 100%;">
  </a>
  <a href="https://api.securityscorecards.dev/projects/github.com/firebase/flutterfire" rel="nofollow">
    <img src="https://camo.githubusercontent.com/92fb38137e5635dd9fb623c77b69ca8fd8f357e75dabbdf2a704488db5ddd8ce/68747470733a2f2f6170692e736563757269747973636f726563617264732e6465762f70726f6a656374732f6769746875622e636f6d2f66697265626173652f666c7574746572666972652f6261646765" alt="OSSF scorecard" data-canonical-src="https://api.securityscorecards.dev/projects/github.com/firebase/flutterfire/badge" style="max-width: 100%;">
  </a>
</p>
<hr>
<p><a href="./CHANGELOG.md">[Changelog]</a> • <a href="https://pub.dev/publishers/firebase.google.com/packages" rel="nofollow">[Packages]</a></p>
<hr>
<p>FlutterFire is a set of <a href="https://flutter.io/platform-plugins/" rel="nofollow">Flutter plugins</a><br>
that enable Flutter apps to use <a href="https://firebase.google.com/" rel="nofollow">Firebase</a> services. You can follow an example that shows<br>
how to use these plugins in<br>
the <a href="https://firebase.google.com/codelabs/firebase-get-to-know-flutter" rel="nofollow">Firebase for Flutter</a> codelab.</p>
<p><a href="https://flutter.dev" rel="nofollow">Flutter</a> is Google’s UI toolkit for building beautiful, natively compiled applications for mobile,<br>
web, and desktop from a single codebase. Flutter is used by developers and organizations around the world, and is free<br>
and open source.</p>
<hr>
<h2>Documentation</h2>
<ul>
<li><a href="https://firebase.google.com/docs/flutter/setup" rel="nofollow">Add Firebase to your Flutter app</a></li>
<li><a href="https://firebase.google.com/docs/flutter/setup#available-plugins" rel="nofollow">Available plugins</a></li>
<li>Firebase UI
<ul>
<li><a href="https://github.com/firebase/FirebaseUI-Flutter/blob/main/packages/firebase_ui_auth/README.md">Firebase UI for Authentication</a></li>
<li><a href="https://github.com/firebase/FirebaseUI-Flutter/blob/main/packages/firebase_ui_database/README.md">Firebase UI for Realtime Database</a></li>
<li><a href="https://github.com/firebase/FirebaseUI-Flutter/blob/main/packages/firebase_ui_firestore/README.md">Firebase UI for Cloud Firestore</a></li>
</ul>
</li>
<li><a href="./packages/cloud_firestore_odm/README.md">Firestore ODM</a> (alpha)</li>
</ul>
<hr>
<h2>Stable Plugins</h2>
<table role="table">
<thead>
<tr>
<th>Name</th>
<th align="center">pub.dev</th>
<th align="center">Firebase Product</th>
<th align="center">Documentation</th>
<th align="center">View Source</th>
<th align="center">Android</th>
<th align="center">iOS</th>
<th align="center">Web</th>
<th align="center">MacOS</th>
</tr>
</thead>
<tbody>
<tr>
<td>Analytics</td>
<td align="center"><a href="https://pub.dev/packages/firebase_analytics" rel="nofollow"><img src="https://camo.githubusercontent.com/44b7183a3be34ddfbf70236bad2a95233c4e51fda4f7a4871a84563af85e3d90/68747470733a2f2f696d672e736869656c64732e696f2f7075622f762f66697265626173655f616e616c79746963732e737667" alt="Analytics pub.dev badge" data-canonical-src="https://img.shields.io/pub/v/firebase_analytics.svg" style="max-width: 100%;"></a></td>
<td align="center"><a href="https://firebase.google.com/products/analytics" rel="nofollow">🔗</a></td>
<td align="center"><a href="https://firebase.flutter.dev/docs/analytics/overview" rel="nofollow">📖</a></td>
<td align="center"><a href="https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_analytics"><code class="notranslate">firebase_analytics</code></a></td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">β</td>
</tr>
<tr>
<td>Authentication</td>
<td align="center"><a href="https://pub.dev/packages/firebase_auth" rel="nofollow"><img src="https://camo.githubusercontent.com/44948cca06f17fcd589bc98e9f8dbccb7de4ba0f37c5ca809a9e0dea02a029e7/68747470733a2f2f696d672e736869656c64732e696f2f7075622f762f66697265626173655f617574682e737667" alt="Authentication pub.dev badge" data-canonical-src="https://img.shields.io/pub/v/firebase_auth.svg" style="max-width: 100%;"></a></td>
<td align="center"><a href="https://firebase.google.com/products/auth" rel="nofollow">🔗</a></td>
<td align="center"><a href="https://firebase.flutter.dev/docs/auth/overview" rel="nofollow">📖</a></td>
<td align="center"><a href="https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth"><code class="notranslate">firebase_auth</code></a></td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">β</td>
</tr>
<tr>
<td>Cloud Firestore</td>
<td align="center"><a href="https://pub.dev/packages/cloud_firestore" rel="nofollow"><img src="https://camo.githubusercontent.com/096526f2a3d24c29cc6456a6a82e2b634176e20a27e1cd212d77f1bceeac14a6/68747470733a2f2f696d672e736869656c64732e696f2f7075622f762f636c6f75645f6669726573746f72652e737667" alt="Cloud Firestore pub.dev badge" data-canonical-src="https://img.shields.io/pub/v/cloud_firestore.svg" style="max-width: 100%;"></a></td>
<td align="center"><a href="https://firebase.google.com/products/firestore" rel="nofollow">🔗</a></td>
<td align="center"><a href="https://firebase.flutter.dev/docs/firestore/overview" rel="nofollow">📖</a></td>
<td align="center"><a href="https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_firestore"><code class="notranslate">cloud_firestore</code></a></td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">β</td>
</tr>
<tr>
<td>Cloud Functions</td>
<td align="center"><a href="https://pub.dev/packages/cloud_functions" rel="nofollow"><img src="https://camo.githubusercontent.com/bb20825ff6aa68bb215b9d146bc5471d271284b5c64a97b1bd9d403160cee1a6/68747470733a2f2f696d672e736869656c64732e696f2f7075622f762f636c6f75645f66756e6374696f6e732e737667" alt="Cloud Functions pub.dev badge" data-canonical-src="https://img.shields.io/pub/v/cloud_functions.svg" style="max-width: 100%;"></a></td>
<td align="center"><a href="https://firebase.google.com/products/functions" rel="nofollow">🔗</a></td>
<td align="center"><a href="https://firebase.flutter.dev/docs/functions/overview" rel="nofollow">📖</a></td>
<td align="center"><a href="https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_functions"><code class="notranslate">cloud_functions</code></a></td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">β</td>
</tr>
<tr>
<td>Cloud Messaging</td>
<td align="center"><a href="https://pub.dev/packages/firebase_messaging" rel="nofollow"><img src="https://camo.githubusercontent.com/ea14c139067a1f60b18379ae68078344863303482d679863909105f07363ddfb/68747470733a2f2f696d672e736869656c64732e696f2f7075622f762f66697265626173655f6d6573736167696e672e737667" alt="Cloud Messaging pub.dev badge" data-canonical-src="https://img.shields.io/pub/v/firebase_messaging.svg" style="max-width: 100%;"></a></td>
<td align="center"><a href="https://firebase.google.com/products/cloud-messaging" rel="nofollow">🔗</a></td>
<td align="center"><a href="https://firebase.flutter.dev/docs/messaging/overview" rel="nofollow">📖</a></td>
<td align="center"><a href="https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging"><code class="notranslate">firebase_messaging</code></a></td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">β</td>
</tr>
<tr>
<td>Cloud Storage</td>
<td align="center"><a href="https://pub.dev/packages/firebase_storage" rel="nofollow"><img src="https://camo.githubusercontent.com/50c5391313e136380298cdd095c099fd47ad7c6157ecbc432b18dafa03f5cb72/68747470733a2f2f696d672e736869656c64732e696f2f7075622f762f66697265626173655f73746f726167652e737667" alt="Cloud Storage pub.dev badge" data-canonical-src="https://img.shields.io/pub/v/firebase_storage.svg" style="max-width: 100%;"></a></td>
<td align="center"><a href="https://firebase.google.com/products/storage" rel="nofollow">🔗</a></td>
<td align="center"><a href="https://firebase.flutter.dev/docs/storage/overview" rel="nofollow">📖</a></td>
<td align="center"><a href="https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_storage"><code class="notranslate">firebase_storage</code></a></td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">β</td>
</tr>
<tr>
<td>Core</td>
<td align="center"><a href="https://pub.dev/packages/firebase_core" rel="nofollow"><img src="https://camo.githubusercontent.com/37715a0d123d9a7a681483248694061ebc4b1586b7c63901b2a15704391d4705/68747470733a2f2f696d672e736869656c64732e696f2f7075622f762f66697265626173655f636f72652e737667" alt="Core pub.dev badge" data-canonical-src="https://img.shields.io/pub/v/firebase_core.svg" style="max-width: 100%;"></a></td>
<td align="center"><a href="https://firebase.google.com" rel="nofollow">🔗</a></td>
<td align="center"><a href="https://firebase.flutter.dev/docs/core/usage" rel="nofollow">📖</a></td>
<td align="center"><a href="https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_core"><code class="notranslate">firebase_core</code></a></td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">β</td>
</tr>
<tr>
<td>Crashlytics</td>
<td align="center"><a href="https://pub.dev/packages/firebase_crashlytics" rel="nofollow"><img src="https://camo.githubusercontent.com/2e00f8b32b0d01ba6ec11ca39b61b59a3fabf7ff5a91d7e37fd89137de4ad1d4/68747470733a2f2f696d672e736869656c64732e696f2f7075622f762f66697265626173655f63726173686c79746963732e737667" alt="Crashlytics pub.dev badge" data-canonical-src="https://img.shields.io/pub/v/firebase_crashlytics.svg" style="max-width: 100%;"></a></td>
<td align="center"><a href="https://firebase.google.com/products/crashlytics" rel="nofollow">🔗</a></td>
<td align="center"><a href="https://firebase.flutter.dev/docs/crashlytics/overview" rel="nofollow">📖</a></td>
<td align="center"><a href="https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_crashlytics"><code class="notranslate">firebase_crashlytics</code></a></td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">N/A</td>
<td align="center">β</td>
</tr>
<tr>
<td>Dynamic Links</td>
<td align="center"><a href="https://pub.dev/packages/firebase_dynamic_links" rel="nofollow"><img src="https://camo.githubusercontent.com/3d6cd2406a4918abd3ac48549287db87825035cee84c6af9cad46d6fea2658fe/68747470733a2f2f696d672e736869656c64732e696f2f7075622f762f66697265626173655f64796e616d69635f6c696e6b732e737667" alt="Dynamic Links pub.dev badge" data-canonical-src="https://img.shields.io/pub/v/firebase_dynamic_links.svg" style="max-width: 100%;"></a></td>
<td align="center"><a href="https://firebase.google.com/products/dynamic-links" rel="nofollow">🔗</a></td>
<td align="center"><a href="https://firebase.flutter.dev/docs/dynamic-links/overview" rel="nofollow">📖</a></td>
<td align="center"><a href="https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_dynamic_links"><code class="notranslate">firebase_dynamic_links</code></a></td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">N/A</td>
<td align="center">N/A</td>
</tr>
<tr>
<td>In-App Messaging</td>
<td align="center"><a href="https://pub.dev/packages/firebase_in_app_messaging" rel="nofollow"><img src="https://camo.githubusercontent.com/114b3261a47daf4111421837cd97c9d94ea88a15dedc083e620fc28d1ff18ae9/68747470733a2f2f696d672e736869656c64732e696f2f7075622f762f66697265626173655f696e5f6170705f6d6573736167696e672e737667" alt="In-App Messaging pub.dev badge" data-canonical-src="https://img.shields.io/pub/v/firebase_in_app_messaging.svg" style="max-width: 100%;"></a></td>
<td align="center"><a href="https://firebase.google.com/products/in-app-messaging" rel="nofollow">🔗</a></td>
<td align="center"><a href="https://firebase.flutter.dev/docs/in-app-messaging/overview" rel="nofollow">📖</a></td>
<td align="center"><a href="https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_in_app_messaging"><code class="notranslate">firebase_in_app_messaging</code></a></td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">N/A</td>
<td align="center">N/A</td>
</tr>
<tr>
<td>Installations</td>
<td align="center"><a href="https://pub.dev/packages/firebase_app_installations" rel="nofollow"><img src="https://camo.githubusercontent.com/dd2caa3074bf2116e87c359e8bf519ea5ecc53c25bacc13707f587ffa7053942/68747470733a2f2f696d672e736869656c64732e696f2f7075622f762f66697265626173655f6170705f696e7374616c6c6174696f6e732e737667" alt="Installations pub.dev badge" data-canonical-src="https://img.shields.io/pub/v/firebase_app_installations.svg" style="max-width: 100%;"></a></td>
<td align="center"><a href="https://firebase.google.com/docs/projects/manage-installations" rel="nofollow">🔗</a></td>
<td align="center"><a href="https://firebase.flutter.dev/docs/installations/overview" rel="nofollow">📖</a></td>
<td align="center"><a href="https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_app_installations"><code class="notranslate">firebase_app_installations</code></a></td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">β</td>
</tr>
<tr>
<td>Performance Monitoring</td>
<td align="center"><a href="https://pub.dev/packages/firebase_performance" rel="nofollow"><img src="https://camo.githubusercontent.com/d2db40ea5df0a9b168facf15539e8c6fb5c8b35b6fba42ab6a162d7f1b701aaf/68747470733a2f2f696d672e736869656c64732e696f2f7075622f762f66697265626173655f706572666f726d616e63652e737667" alt="Performance Monitoring pub.dev badge" data-canonical-src="https://img.shields.io/pub/v/firebase_performance.svg" style="max-width: 100%;"></a></td>
<td align="center"><a href="https://firebase.google.com/products/performance" rel="nofollow">🔗</a></td>
<td align="center"><a href="https://firebase.flutter.dev/docs/performance/overview" rel="nofollow">📖</a></td>
<td align="center"><a href="https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_performance"><code class="notranslate">firebase_performance</code></a></td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">N/A</td>
</tr>
<tr>
<td>Realtime Database</td>
<td align="center"><a href="https://pub.dev/packages/firebase_database" rel="nofollow"><img src="https://camo.githubusercontent.com/16d81263416128179825f74a9de9f7bdecaaa69f937975f29fab2a7156e96fd6/68747470733a2f2f696d672e736869656c64732e696f2f7075622f762f66697265626173655f64617461626173652e737667" alt="Realtime Database pub.dev badge" data-canonical-src="https://img.shields.io/pub/v/firebase_database.svg" style="max-width: 100%;"></a></td>
<td align="center"><a href="https://firebase.google.com/products/database" rel="nofollow">🔗</a></td>
<td align="center"><a href="https://firebase.flutter.dev/docs/database/overview" rel="nofollow">📖</a></td>
<td align="center"><a href="https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_database"><code class="notranslate">firebase_database</code></a></td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">β</td>
</tr>
<tr>
<td>Remote Config</td>
<td align="center"><a href="https://pub.dev/packages/firebase_remote_config" rel="nofollow"><img src="https://camo.githubusercontent.com/30c89211a62adae002a61452c6bd1bf93f8a3f8dcefc5a39e55460d70003fa88/68747470733a2f2f696d672e736869656c64732e696f2f7075622f762f66697265626173655f72656d6f74655f636f6e6669672e737667" alt="Remote Config pub.dev badge" data-canonical-src="https://img.shields.io/pub/v/firebase_remote_config.svg" style="max-width: 100%;"></a></td>
<td align="center"><a href="https://firebase.google.com/products/remote-config" rel="nofollow">🔗</a></td>
<td align="center"><a href="https://firebase.flutter.dev/docs/remote-config/overview" rel="nofollow">📖</a></td>
<td align="center"><a href="https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_remote_config"><code class="notranslate">firebase_remote_config</code></a></td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">β</td>
</tr>
</tbody>
</table>
<h2>Beta Plugins</h2>
<table role="table">
<thead>
<tr>
<th>Name</th>
<th align="center">pub.dev</th>
<th align="center">Firebase Product</th>
<th align="center">Documentation</th>
<th align="center">View Source</th>
<th align="center">Android</th>
<th align="center">iOS</th>
<th align="center">Web</th>
<th align="center">MacOS</th>
</tr>
</thead>
<tbody>
<tr>
<td>App Check</td>
<td align="center"><a href="https://pub.dev/packages/firebase_app_check" rel="nofollow"><img src="https://camo.githubusercontent.com/d0c15f4473d4c54afbfc9901e82ce41d713a6e206f195440fa1d292e604f8bf9/68747470733a2f2f696d672e736869656c64732e696f2f7075622f762f66697265626173655f6170705f636865636b2e737667" alt="App Check pub.dev badge" data-canonical-src="https://img.shields.io/pub/v/firebase_app_check.svg" style="max-width: 100%;"></a></td>
<td align="center"><a href="https://firebase.google.com/docs/app-check" rel="nofollow">🔗</a></td>
<td align="center"><a href="https://firebase.flutter.dev/docs/app-check/overview" rel="nofollow">📖</a></td>
<td align="center"><a href="https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_app_check"><code class="notranslate">firebase_app_check</code></a></td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">β</td>
</tr>
</tbody>
</table>
<h2>Preview Plugins</h2>
<table role="table">
<thead>
<tr>
<th>Name</th>
<th align="center">pub.dev</th>
<th align="center">Firebase Product</th>
<th align="center">Documentation</th>
<th align="center">View Source</th>
<th align="center">Android</th>
<th align="center">iOS</th>
<th align="center">Web</th>
<th align="center">MacOS</th>
</tr>
</thead>
<tbody>
<tr>
<td>ML Model Downloader</td>
<td align="center"><a href="https://pub.dev/packages/firebase_ml_model_downloader" rel="nofollow"><img src="https://camo.githubusercontent.com/1b54e47e25d752fde6c3312f5fc027061155e90c3841dbb8c91d333b0dc592b8/68747470733a2f2f696d672e736869656c64732e696f2f7075622f762f66697265626173655f6d6c5f6d6f64656c5f646f776e6c6f616465722e737667" alt="ML Model Downloader pub.dev badge" data-canonical-src="https://img.shields.io/pub/v/firebase_ml_model_downloader.svg" style="max-width: 100%;"></a></td>
<td align="center"><a href="https://firebase.google.com/products/ml" rel="nofollow">🔗</a></td>
<td align="center"><a href="https://firebase.flutter.dev/docs/ml-model-downloader/overview" rel="nofollow">📖</a></td>
<td align="center"><a href="https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_ml_model_downloader"><code class="notranslate">firebase_ml_model_downloader</code></a></td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">N/A</td>
<td align="center">β</td>
</tr>
</tbody>
</table>
<h2>Alpha Plugins</h2>
<table role="table">
<thead>
<tr>
<th>Name</th>
<th align="center">pub.dev</th>
<th align="center">Firebase Product</th>
<th align="center">Documentation</th>
<th align="center">View Source</th>
<th align="center">Android</th>
<th align="center">iOS</th>
<th align="center">Web</th>
<th align="center">MacOS</th>
</tr>
</thead>
<tbody>
<tr>
<td>Cloud Firestore ODM</td>
<td align="center"><a href="https://pub.dev/packages/cloud_firestore_odm" rel="nofollow"><img src="https://camo.githubusercontent.com/e598468d2b62f1842f17188f4453372b5e58803322e7b05ce9f9744ed7555058/68747470733a2f2f696d672e736869656c64732e696f2f7075622f762f636c6f75645f6669726573746f72655f6f646d2e737667" alt="Cloud Firestore ODM pub.dev badge" data-canonical-src="https://img.shields.io/pub/v/cloud_firestore_odm.svg" style="max-width: 100%;"></a></td>
<td align="center"><a href="https://firebase.google.com" rel="nofollow">🔗</a></td>
<td align="center"><a href="https://firebase.flutter.dev/docs/firestore-odm/overview" rel="nofollow">📖</a></td>
<td align="center"><a href="https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_firestore_odm"><code class="notranslate">cloud_firestore_odm</code></a></td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">✔</td>
<td align="center">β</td>
</tr>
</tbody>
</table>
<h2>Issues</h2>
<p>Please file FlutterFire specific issues, bugs, or feature requests in<br>
our <a href="https://github.com/firebase/flutterfire/issues/new/choose">issue tracker</a>.</p>
<p>Plugin issues that are not specific to FlutterFire can be filed in<br>
the <a href="https://github.com/flutter/flutter/issues/new">Flutter issue tracker</a>.</p>
<h2>Contributing</h2>
<p>If you wish to contribute a change to any of the existing plugins in this repo, please review<br>
our <a href="https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md">contribution guide</a><br>
and open a <a href="https://github.com/firebase/flutterfire/pulls">pull request</a>.</p>
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
   HtmlWidget(html);
```
</details>

<details>
  <summary>Tesing environment</summary>

```
[✓] Flutter (Channel stable, 3.13.7, on macOS 13.5.1 22G90 darwin-arm64, locale en-IN)
    • Flutter version 3.13.7 on channel stable at /opt/homebrew/Caskroom/flutter/3.3.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f708eb839 (8 days ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/naman/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```
</details>

## Expected results

a table

## Actual results
no table and all the content got stacked

Breaking at:https://github.com/daohoangson/flutter_widget_from_html/blob/5304c06f4195af9fb81bba1f4850d7b0a348e197/packages/core/lib/src/widgets/html_table.dart#L834

<details>
    <summary>Stack Trace</summary>

```
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1965:12)
#3      _TableRenderObject.paint (package:flutter_widget_from_html_core/src/widgets/html_table.dart:834:23)
#4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#6      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#7      _ValignBaselineClearerRenderObject.paint (package:flutter_widget_from_html_core/src/widgets/valign_baseline.dart:98:11)
#8      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#9      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#10     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2875:15)
#11     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1040:7)
#12     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#13     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#14     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#15     RenderAnimatedOpacityMixin.paint (package:flutter/src/rendering/proxy_box.dart:1060:11)
#16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#17     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:168:11)
#18     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:111:5)
#19     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1144:31)
#20     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:496:19)
#21     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:918:13)
#22     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
#23     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#24     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#25     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:5)
#26     _invoke (dart:ui/hooks.dart:170:13)
#27     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
#28     _drawFrame (dart:ui/hooks.dart:140:31)
(elided 2 frames from class _AssertionError)
```
</details>

![image](https://github.com/daohoangson/flutter_widget_from_html/assets/33877135/6c2c23e9-84ea-4b8c-8277-22746a3d7e3b)

**Comment by NamanShergill** [comment]
This is on the latest version `0.14.2`

**Comment by NamanShergill** [comment]
Yep, it’s working now. Thanks again for such a quick fix!
