### ISSUE TITLE
Exception during testing: "setState() called after dispose()"

### ISSUE THREAD

**Issue by daohoangson** [daohoangson/flutter_widget_from_html#236]
This doesn't prevent the tests from running or trigger any further error but it should be investigated and preferably fixed.

<details>

<summary>flutter test</summary>

```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following assertion was thrown when reporting an error to an image listener:
setState() called after dispose(): _ImageState#cfbe1(lifecycle state: defunct, not mounted, stream:
ImageStream#199de(MultiFrameImageStreamCompleter#9e831, [192×192] @ 1.0x, 1 listener), pixels: null,
loadingProgress: null, frameNumber: null, wasSynchronouslyLoaded: false)
This error happens if you call setState() on a State object for a widget that no longer appears in
the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error
can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose()
callback. Another solution is to check the "mounted" property of this object before calling
setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is
retaining a reference to this State object after it has been removed from the tree. To avoid memory
leaks, consider breaking the reference to this object during dispose().

When the exception was thrown, this was the stack:
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1197:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1232:6)
#2      _ImageState._getListener.<anonymous closure> (package:flutter/src/widgets/image.dart:1135:15)
#3      ImageStreamCompleter.reportError (package:flutter/src/painting/image_stream.dart:504:24)
#4      ImageStreamCompleter.setImage (package:flutter/src/painting/image_stream.dart:439:9)
#5      MultiFrameImageStreamCompleter._emitFrame (package:flutter/src/painting/image_stream.dart:739:5)
#6      MultiFrameImageStreamCompleter._decodeNextFrameAndSchedule (package:flutter/src/painting/image_stream.dart:724:7)
<asynchronous suspension>
#7      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:674:7)
#19     AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart)
<asynchronous suspension>
#20     AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:648:14)
#21     ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:501:13)
#22     ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:359:22)
#23     ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:499:80)
#24     ScrollAwareImageProvider.resolveStreamForKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:106:19)
#25     ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:330:9)
#26     ImageProvider._createErrorHandlerAndKey.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:460:26)
#39     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:881:25)
#42     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#43     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:866:27)
#44     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:441:22)
#47     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#48     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:438:27)
#49     explain (file:///Users/sondh/repos/flutter.d/flutter_widget_from_html/packages/core/test/_.dart:50:16)
#50     explain (file:///Users/sondh/repos/flutter.d/flutter_widget_from_html/test/_.dart:56:5)
#51     main.<anonymous closure>.<anonymous closure> (file:///Users/sondh/repos/flutter.d/flutter_widget_from_html/test/tag_video_test.dart:68:31)
#52     main.<anonymous closure>.<anonymous closure> (file:///Users/sondh/repos/flutter.d/flutter_widget_from_html/test/tag_video_test.dart:65:52)
#53     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:140:29)
#66     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1099:17)
#67     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1087:35)
(elided 54 frames from class _FakeAsync, dart:async, dart:async-patch, and package:stack_trace)
```
</details>

**Comment by daohoangson** [comment]
Apparently an issue with Flutter latest stable as reported here https://github.com/flutter/flutter/issues/61324, let's wait for the next release.

**Comment by OHeroJ** [comment]
i think can use provider.  

```dart
class StateViewModel extends ChangeNotifier {
 
  /// 防止页面销毁后，异步任务才完成，导致报错
  bool _disposed = false;


  @override
  void notifyListeners() {
    if (!_disposed) {
      super.notifyListeners();
    }
  }

  @override
  void dispose() {
    _disposed = true;
    super.dispose();
  }
}
```

**Comment by daohoangson** [comment]
This is a mishap deep inside image pipeline, there is not much we can do. Just make sure you are running an up to date Flutter version and it should go away.
