### ISSUE TITLE
If the image is small, such as 90 * 90(px). How to make its width equal to the screen width

### ISSUE THREAD

**Issue by OHeroJ** [daohoangson/flutter_widget_from_html#331]
```html
<div><img src="xxx.png"></div>
```

at  `_ImageLayoutDelegate`:

```dart
@override
  Size getSize(BoxConstraints bc) {
    final w = width < bc.maxWidth ? width : bc.maxWidth;
    final h = height < bc.maxHeight ? height : bc.maxHeight;
    if (w == width && h == height) return Size(w, h);

    final r = w / h;
    if (r < ratio) return Size(w, w / ratio);

    return Size(h * ratio, h);
  }
```

Can users choose the way to adapt the small picture? 

Or provide the minimum width parameter for setting the picture, at `HtmlWidgetConfig`:  

```dart
final double imgMinWidth;
```

**Comment by daohoangson** [comment]
You want to scale up the small image? This may result in pixelated images, are you sure?

Technically this should be possible with the inline style `width: 100%` but this package doesn't support percentage dimensions yet...

**Comment by OHeroJ** [comment]
> You want to scale up the small image? This may result in pixelated images, are you sure?
> 
> Technically this should be possible with the inline style `width: 100%` but this package doesn't support percentage dimensions yet...

I am using the version 0.3.3+4, and then I made a modification， https://github.com/OHeroJ/flutter_widget_from_html/commit/334c3985608ac5aea1d3bc6eeb443db1186a0f51

**Comment by daohoangson** [comment]
Is there any reason why you are using a release that old? The stable version is 0.5 already.

And if you can set a min width in pixel, using `min-width: 123px` should be good enough for you. You can set this inline style for all `IMG` with `customStylesBuilder` (this requires version 0.5)

**Comment by OHeroJ** [comment]
> Is there any reason why you are using a release that old? The stable version is 0.5 already.
> 
> And if you can set a min width in pixel, using `min-width: 123px` should be good enough for you. You can set this inline style for all `IMG` with `customStylesBuilder` (this requires version 0.5)

just use  flutter 1.17.1

**Comment by daohoangson** [comment]
I think version `0.5.0+4` may work with Flutter 1.17. you really should not using 0.3 at this point, there so many improvements since then...

**Comment by OHeroJ** [comment]
> I think version `0.5.0+4` may work with Flutter 1.17. you really should not using 0.3 at this point, there so many improvements since then...


I will upgrade now

**Comment by daohoangson** [comment]
Thank you for your kind words. How did the upgrade go?

**Comment by OHeroJ** [comment]
The update was successful, but

```dart
HtmlWidget(
                    model.info.companyprofile,
                    textStyle: TextStyle(fontSize: 14, color: Color(0xff333333), height: 1.5),
                    customStylesBuilder: (element) {
                      if (element.localName.toLowerCase() == 'img') {
                        return {'width': '300px'};
                      }
                      return null;
                    },
                  )
```

**Comment by OHeroJ** [comment]
> Thank you for your kind words. How did the upgrade go?

The update was successful, but

```dart
HtmlWidget(
        model.info.companyprofile,
        textStyle: TextStyle(fontSize: 14, color: Color(0xff333333), height: 1.5),
        customStylesBuilder: (element) {
             if (element.localName.toLowerCase() == 'img') {
                       return {'width': '300px'};
             }
             return null;
          },
)
```

**Comment by daohoangson** [comment]
You don't need the `toLowerCase`, that is done automatically. Also, can you share the HTML? I'll try to reproduce from my end.

**Comment by OHeroJ** [comment]
> You don't need the `toLowerCase`, that is done automatically. Also, can you share the HTML? I'll try to reproduce from my end.

```html
<p><p>哈哈哈哈</p>哈哈哈哈哈哈哈睡觉睡觉哈哈哈</p><p>阿斯达阿斯达阿斯达</p><p><img src=\"https://cdn36.hipicbeta.com/lifeimage/2020/20200929/2848f1923e96ff42f6e4.jpg\" xss=removed><br></p>
```

**Comment by OHeroJ** [comment]
```
flutter: The following assertion was thrown when reporting an error to an image listener:
flutter: setState() called after dispose(): _ImageState#345dc(lifecycle state: defunct, not mounted, stream:
flutter: ImageStream#29212(MultiFrameImageStreamCompleter#343a8, [192×192] @ 1.0x, 2 listeners), pixels:
flutter: null, loadingProgress: null, frameNumber: null, wasSynchronouslyLoaded: false)
flutter: This error happens if you call setState() on a State object for a widget that no longer appears in
flutter: the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error
flutter: can occur when code calls setState() from a timer or an animation callback.
flutter: The preferred solution is to cancel the timer or stop listening to the animation in the dispose()
flutter: callback. Another solution is to check the "mounted" property of this object before calling
flutter: setState() to ensure the object is still in the tree.
flutter: This error might indicate a memory leak if setState() is being called because another object is
flutter: retaining a reference to this State object after it has been removed from the tree. To avoid memory
flutter: leaks, consider breaking the reference to this object during dispose().
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1197:9)
flutter: #1      State.setState (package:flutter/src/widgets/framework.dart:1232:6)
flutter: #2      _ImageState._getListener.<anonymous closure> (package:flutter/src/widgets/image.dart:1116:13)
flutter: #3      ImageStreamCompleter.reportError (package:flutter/src/painting/image_stream.dart:504:24)
flutter: #4      ImageStreamCompleter.setImage (package:flutter/src/painting/image_stream.dart:439:9)
flutter: #5      MultiFrameImageStreamCompleter._emitFrame (package:flutter/src/painting/image_stream.dart:739:5)
flutter: #6      MultiFrameImageStreamCompleter._decodeNextFrameAndSchedule (package:flutter/src/painting/image_stream.dart:724:7)
flutter: <asynchronous suspension>
flutter: #7      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:674:7)
flutter: #22     CachedNetworkImageProvider._loadAsync (package:cached_network_image/src/image_provider/_image_provider_io.dart)
flutter: <asynchronous suspension>
flutter: #23     CachedNetworkImageProvider.load (package:cached_network_image/src/image_provider/_image_provider_io.dart:54:14)
flutter: #24     ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:501:13)
flutter: #25     ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:359:22)
flutter: #26     ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:499:80)
flutter: #27     ScrollAwareImageProvider.resolveStreamForKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:106:19)
flutter: #28     ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:330:9)
flutter: #29     ImageProvider._createErrorHandlerAndKey.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:460:26)
flutter: #30     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:41:29)
flutter: #31     ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:457:11)
flutter: #35     ImageProvider._createErrorHandlerAndKey (package:flutter/src/painting/image_provider.dart:449:16)
flutter: #36     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:327:5)
flutter: #37     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:1099:16)
flutter: #38     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:1052:5)
flutter: #39     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4661:12)
flutter: #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
flutter: ...     Normal element mounting (13 frames)
flutter: #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
flutter: #54     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
flutter: ...     Normal element mounting (10 frames)
flutter: #64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
flutter: #65     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
flutter: ...     Normal element mounting (64 frames)
flutter: #129    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
flutter: #130    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
flutter: ...     Normal element mounting (43 frames)
flutter: #173    _RegisteredElement.mount (package:scrollable_positioned_list/src/element_registry.dart:69:11)
flutter: ...     Normal element mounting (30 frames)
flutter: #203    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
flutter: #204    Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
flutter: #205    SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1162:36)
flutter: #206    SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1147:20)
flutter: #207    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
flutter: #208    SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1140:11)
flutter: #209    RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:354:23)
flutter: #210    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1866:58)
flutter: #211    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:918:15)
flutter: #212    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1866:13)
flutter: #213    RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:343:5)
flutter: #214    RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:489:5)
flutter: #215    RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:219:19)
flutter: #216    RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:262:19)
flutter: #217    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #218    RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:135:11)
flutter: #219    RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:375:11)
flutter: #220    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #221    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:452:13)
flutter: #222    UnboundedRenderViewport._attemptLayout (package:scrollable_positioned_list/src/viewport.dart:239:12)
flutter: #223    UnboundedRenderViewport.performLayout (package:scrollable_positioned_list/src/viewport.dart:150:20)
flutter: #224    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #225    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #226    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #227    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #228    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #229    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #230    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #231    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #232    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #233    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #234    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #235    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #236    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #237    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:246:13)
flutter: #238    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #239    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #240    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #241    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:556:15)
flutter: #242    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #243    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #244    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #245    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #246    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #247    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:556:15)
flutter: #248    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #249    RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:207:11)
flutter: #250    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #251    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:556:15)
flutter: #252    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #253    RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:808:17)
flutter: #254    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #255    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:11)
flutter: #256    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:484:7)
flutter: #257    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
flutter: #258    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:399:14)
flutter: #259    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #260    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #261    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #262    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #263    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1248:11)
flutter: #264    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #265    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:556:15)
flutter: #266    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #267    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #268    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1630:7)
flutter: #269    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
flutter: #270    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:402:19)
flutter: #271    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:13)
flutter: #272    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
flutter: #273    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
flutter: #274    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
flutter: #275    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
flutter: #279    _invoke (dart:ui/hooks.dart:261:10)
flutter: #280    _drawFrame (dart:ui/hooks.dart:219:3)
flutter: (elided 20 frames from dart:async and dart:async-patch)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: CachedNetworkImageProvider("https://cdn36.hipicbeta.com/lifeimage/2020/20200929/2848f1923e96ff42f6e4.jpg", scale: 1.0) error: setState() called after dispose(): _ImageState#345dc(lifecycle state: defunct, not mounted, stream: ImageStream#29212(MultiFrameImageStreamCompleter#343a8, [192×192] @ 1.0x, 2 listeners), pixels: null, loadingProgress: null, frameNumber: null, wasSynchronouslyLoaded: false)
or a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
ng to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
g called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
Received memory pressure event 2 vm pressure 0
```

**Comment by daohoangson** [comment]
> flutter: setState() called after dispose(): 

Probably related to #236, which is a Flutter issue that has been fixed by Flutter team. Make sure you are on the latest stable maybe?

I'm testing your example HTML above, will report back soon.

**Comment by daohoangson** [comment]
Hmm, 🤔 the IMG ignores all constraints to avoid scaling up... I'll see what can be done here.

**Comment by OHeroJ** [comment]
> > flutter: setState() called after dispose():
> 
> Probably related to #236, which is a Flutter issue that has been fixed by Flutter team. Make sure you are on the latest stable maybe?
> 
> I'm testing your example HTML above, will report back soon.

i think use provider,  https://github.com/daohoangson/flutter_widget_from_html/issues/236#issuecomment-701121726

**Comment by OHeroJ** [comment]
> Hmm, 🤔 the IMG ignores all constraints to avoid scaling up... I'll see what can be done here.

```dart
Widget buildImage(BuildMetadata meta, Object provider, ImageMetadata data) {
    if (provider == null) return null;
    if (provider is ImageProvider) {
      final semanticLabel = data?.alt ?? data?.title;
      return Image(
        errorBuilder: (_, error, __) {
          print('$provider error: $error');
          final text = semanticLabel ?? '❌';
          return Text(text);
        },
        excludeFromSemantics: semanticLabel == null,
        image: provider,
        semanticLabel: semanticLabel,
      );
    }

    return null;
  }
```

**Comment by daohoangson** [comment]
`v0.5.1` has been released with the fix for you, it's now possible to use `width: 123px` to resize an image. Please try upgrading and let me know if it works for you.
