### ISSUE TITLE
Cannot scroll in some spot. [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'dart:ui/geometry.dart': Failed assertion: line 1186: '<optimized out>': is not true.

### ISSUE THREAD

**Issue by daffaalam** [daohoangson/flutter_widget_from_html#405]
cannot scroll on this spot (the distance between `</p>` and `<p>`)

![image](https://user-images.githubusercontent.com/30487820/103482628-7558d300-4e14-11eb-85f9-b2c5209f03f2.png)

There are no errors during rendering, but when trying to scroll at that spot, an error will appear

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'dart:ui/geometry.dart': Failed assertion: line 1186: '<optimized out>': is not true.
E/flutter (19083): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (19083): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (19083): #2      new RRect._raw (dart:ui/geometry.dart:1186:15)
E/flutter (19083): #3      new RRect.fromRectAndCorners (dart:ui/geometry.dart:1154:12)
E/flutter (19083): #4      BorderRadius.toRRect (package:flutter/src/painting/border_radius.dart:371:18)
E/flutter (19083): #5      BoxDecoration.hitTest (package:flutter/src/painting/box_decoration.dart:364:69)
E/flutter (19083): #6      RenderDecoratedBox.hitTestSelf (package:flutter/src/rendering/proxy_box.dart:2068:24)
E/flutter (19083): #7      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:58)
E/flutter (19083): #8      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:122:19)
E/flutter (19083): #9      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (19083): #10     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:122:19)
E/flutter (19083): #11     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (19083): #12     RenderSliverHelpers.hitTestBoxChild.<anonymous closure> (package:flutter/src/rendering/sliver.dart:1671:22)
E/flutter (19083): #13     BoxHitTestResult.addWithOutOfBandPosition (package:flutter/src/rendering/box.dart:882:31)
E/flutter (19083): #14     RenderSliverHelpers.hitTestBoxChild (package:flutter/src/rendering/sliver.dart:1668:19)
E/flutter (19083): #15     RenderSliverMultiBoxAdaptor.hitTestChildren (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:559:11)
E/flutter (19083): #16     RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1289:11)
E/flutter (19083): #17     SliverHitTestResult.addWithAxisOffset (package:flutter/src/rendering/sliver.dart:859:31)
E/flutter (19083): #18     RenderSliverEdgeInsetsPadding.hitTestChildren (package:flutter/src/rendering/sliver_padding.dart:218:14)
E/flutter (19083): #19     RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1289:11)
E/flutter (19083): #20     RenderViewportBase.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/viewport.dart:698:24)
E/flutter (19083): #21     BoxHitTestResult.addWithOutOfBandPosition (package:flutter/src/rendering/box.dart:882:31)
E/flutter (19083): #22     RenderViewportBase.hitTestChildren (package:flutter/src/rendering/viewport.dart:695:33)
E/flutter (19083): #23     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (19083): #24     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:122:19)
E/flutter (19083): #25     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (19083): #26     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3118:31)
E/flutter (19083): #27     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:122:19)
E/flutter (19083): #28     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (19083): #29     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:122:19)
E/flutter (19083): #30     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:169:19)
E/flutter (19083): #31     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:122:19)
E/flutter (19083): #32     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (19083): #33     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:122:19)
E/flutter (19083): #34     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:169:19)
E/flutter (19083): #35     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:122:19)
E/flutter (19083): #36     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (19083): #37     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:122:19)
E/flutter (19083): #38     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (19083): #39     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:122:19)
E/flutter (19083): #40     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:508:18)
E/flutter (19083): #41     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (19083): #42     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:122:19)
E/flutter (19083): #43     RenderBox.hitT
```

**Comment by daohoangson** [comment]
Can you share your HTML? There seems to be issue when that space is being painted.

**Comment by daffaalam** [comment]
> 
> 
> Can you share your HTML? There seems to be issue when that space is being painted.

HTML
```html
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<p></p>Urna molestie at elementum eu facilisis sed odio morbi quis.</p>
```

Flutter
```dart
...
ListView(
  children: <Widget>[
    ...
    Container(
      padding: EdgeInsets.all(16.0),
      child: HtmlWidget(
        text,
      ),
    ),
    ...
  ],
),
...
```

**Comment by daohoangson** [comment]
I know this is an old issue but I have just tried reproducing this and failed. I feel a feeling this might happen because of a Flutter bug and it has been fixed in some recent version. Please try again and let me know if you are still having problems.
