### ISSUE TITLE
Table with <td style="text-align: center;"> and image cannot be rendered

### ISSUE THREAD

**Issue by DFelten** [daohoangson/flutter_widget_from_html#851]
It seems there is a bug for a table with `<td style="text-align: center;">` and an image. The complete html cannot be rendered. An error is displayed in the console and nothing appears.

## Steps to Reproduce

<details>
  <summary>HTML</summary>

```html
<div class="table-responsive">
    <table class="table table-striped mce-table mce-row-header">
        <thead>
            <tr>
                <th>Aktion</th>
                <th>Besonderheiten</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td style="text-align: center;">
                    <p>
                        <img src="https://www.kostenlos.de/app/uploads/2022/08/iglo_Green_Cuisine_Produkte.jpg">
                    </p>
                 
                </td>
                <td>
                    <p>max. 13.333 Einlösungen</p>
                </td>
            </tr>
           
        </tbody>
    </table>
</div>
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
```
</details>

<details>
  <summary>Tesing environment</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.1 22C65 darwin-arm, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
[✓] VS Code (version 1.74.2)
[✓] VS Code (version 1.75.0-insider)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```
</details>

## Expected results

A table with two columns.

This is how it looks in the browser:

![CleanShot 2023-01-05 at 16 53 52](https://user-images.githubusercontent.com/1169185/210823557-b00af2dc-dc49-440c-ae61-a0e321edfba6.png)

## Actual results

Nothing, the html cannot render.

<details>
  <summary>Console error</summary>

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
The RenderParagraph class does not support dry layout.
Dry layout not available for alignments that require baseline.

The relevant error-causing widget was:
  HtmlWidget
  HtmlWidget:file:///Users/danielfelten/Projekte/Trimexa/kostenlos/framework/packages/html/lib/src/widgets/tmx_html_widget.dart:51:22

When the exception was thrown, this was the stack:
#0      RenderBox.debugCannotComputeDryLayout.<anonymous closure> (package:flutter/src/rendering/box.dart:1986:11)
box.dart:1986
#1      RenderBox.debugCannotComputeDryLayout (package:flutter/src/rendering/box.dart:1996:6)
box.dart:1996
#2      RenderParagraph.computeDryLayout (package:flutter/src/rendering/paragraph.dart:757:14)
paragraph.dart:757
#3      RenderBox._computeDryLayout (package:flutter/src/rendering/box.dart:1909:25)
box.dart:1909
#4      RenderBox.getDryLayout.<anonymous closure> (package:flutter/src/rendering/box.dart:1891:81)
box.dart:1891
#5      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:527:23)
#6      RenderBox.getDryLayout (package:flutter/src/rendering/box.dart:1891:50)
box.dart:1891
#7      _RenderCssSizing.computeDryLayout (package:flutter_widget_from_html_core/src/widgets/css_sizing.dart:196:30)
css_sizing.dart:196
#8      RenderBox._computeDryLayout (package:flutter/src/rendering/box.dart:1909:25)
box.dart:1909
#9      RenderBox.getDryLayout.<anonymous closure> (package:flutter/src/rendering/box.dart:1891:81)
box.dart:1891
#10     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:527:23)
#11     RenderBox.getDryLayout (package:flutter/src/rendering/box.dart:1891:50)
box.dart:1891
#12     ChildLayoutHelper.dryLayoutChild (package:flutter/src/rendering/layout_helper.dart:39:18)
layout_helper.dart:39
#13     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:836:43)
flex.dart:836
#14     RenderFlex.computeDryLayout (package:flutter/src/rendering/flex.dart:697:32)
flex.dart:697
#15     RenderBox._computeDryLayout (package:flutter/src/rendering/box.dart:1909:25)
box.dart:1909
#16     RenderBox.getDryLayout.<anonymous closure> (package:flutter/src/rendering/box.dart:1891:81)
box.dart:1891
#17     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:527:23)
#18     RenderBox.getDryLayout (package:flutter/src/rendering/box.dart:1891:50)
box.dart:1891
#19     RenderPadding.computeDryLayout (package:flutter/src/rendering/shifted_box.dart:229:35)
shifted_box.dart:229
#20     RenderBox._computeDryLayout (package:flutter/src/rendering/box.dart:1909:25)
box.dart:1909
#21     RenderBox.getDryLayout.<anonymous closure> (package:flutter/src/rendering/box.dart:1891:81)
box.dart:1891
#22     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:527:23)
#23     RenderBox.getDryLayout (package:flutter/src/rendering/box.dart:1891:50)
box.dart:1891
#24     RenderPositionedBox.computeDryLayout (package:flutter/src/rendering/shifted_box.dart:432:37)
shifted_box.dart:432
#25     RenderBox._computeDryLayout (package:flutter/src/rendering/box.dart:1909:25)
box.dart:1909
#26     RenderBox.getDryLayout.<anonymous closure> (package:flutter/src/rendering/box.dart:1891:81)
box.dart:1891
#27     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:527:23)
#28     RenderBox.getDryLayout (package:flutter/src/rendering/box.dart:1891:50)
box.dart:1891
#29     _TableRenderObject._performLayoutDry (package:flutter_widget_from_html_core/src/widgets/html_table.dart:578:17)
html_table.dart:578
#30     _TableRenderObject._performLayout (package:flutter_widget_from_html_core/src/widgets/html_table.dart:424:22)
html_table.dart:424
#31     _TableRenderObject.performLayout (package:flutter_widget_from_html_core/src/widgets/html_table.dart:383:15)
html_table.dart:383
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
object.dart:2135
#33     RenderBox.layout (package:flutter/src/rendering/box.dart:2450:11)
box.dart:2450
#34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
proxy_box.dart:120
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
object.dart:2135
#36     RenderBox.layout (package:flutter/src/rendering/box.dart:2450:11)
box.dart:2450
#37     _RenderCssSizing.performLayout (package:flutter_widget_from_html_core/src/widgets/css_sizing.dart:203:12)
css_sizing.dart:203
#38     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
object.dart:2135
#39     RenderBox.layout (package:flutter/src/rendering/box.dart:2450:11)
box.dart:2450
#40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
proxy_box.dart:120
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
object.dart:213
```
</details>

**Comment by daohoangson** [comment]
This PR #846 should fix your issue already. Please try running the latest master or wait for the next release, which will include the fix.

**Comment by DFelten** [comment]
Thanks, it's working with the latest master.
